name: computational_modeling_hci
channels:
  - conda-forge
  - kgullikson
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - pandas
  - scikit-learn
  - pip
  - pip:
    - gpy
    - gpyopt
    - gym
    - jupyter
